// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.js
export const metadata = {
  title: 'Ok Chef',
  description: 'Carnet de recettes connecté à WordPress',
};

import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import ParallaxProviderClient from './parallaxe/ParallaxeProviderClient';

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="bg-jaune text-brun min-h-screen flex flex-col">
      <ParallaxProviderClient>
        <Navbar />
        <main className="contenu-app-page">{children}</main>
        <Footer />
      </ParallaxProviderClient>
      </body>
    </html>
  );
}